dist: xenial
sudo: required
language: python
python:
- "3.6"
- "3.7"

install:
- pip install coveralls pycodestyle tox-travis

script:
- pycodestyle --max-line-length=120 pccora
- coverage run --source pccora setup.py test
- tox

after_success:
  coveralls
