dist: xenial
sudo: required
language: python
python: "3.5"

install:
- pip install coveralls

script:
  - pycodestyle --max-line-length=120 pccora
  - coverage run --source pccora setup.py test

after_success:
  coveralls
